import { chromium, expect } from '@playwright/test'
import assert from 'node:assert/strict'
import { writeFile } from 'node:fs/promises'

const browser = await chromium.launch({ channel: 'chrome' })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 }, reducedMotion: 'no-preference' })
const evidence = []
const errors = []
page.on('pageerror', error => errors.push(error.message))
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' })
await expect(page.locator('.hero-content')).toHaveCSS('opacity', '1')
assert.equal(await page.locator('.hero-content').evaluate(el => getComputedStyle(el).animationIterationCount), '1')
evidence.push('Hero entrance finishes with readable content; animation runs once')

const plants = page.locator('[data-botanical]')
assert.deepEqual(await plants.evaluateAll(elements => elements.map(el => el.dataset.botanical)), ['olive-lavender', 'olive-lavender', 'olive-lavender', 'olive-lavender'])
const firstService = page.locator('.service-row').first()
await expect(firstService).toHaveCSS('opacity', '0')
const foliage = plants.first()
const foliageArt = foliage.locator('svg').first()
await expect(foliageArt).toHaveCSS('opacity', '0.1')
await expect(foliage.locator('[data-plant="lavender"]')).toHaveCSS('opacity', '0.065')
await expect(foliage).toHaveCSS('opacity', '0')
await page.locator('#booking-options').evaluate(el => scrollTo({ top: scrollY + el.getBoundingClientRect().top - innerHeight * .7, behavior: 'instant' }))
await expect(foliage).toHaveCSS('opacity', '0')
await page.locator('#booking-options').evaluate(el => scrollTo({ top: scrollY + el.getBoundingClientRect().top - innerHeight * .5, behavior: 'instant' }))
await page.waitForFunction(() => {
  const opacity = Number(getComputedStyle(document.querySelector('[data-botanical]')).opacity)
  return opacity > 0 && opacity < 1
})
await page.screenshot({ path: 'test-results/desktop-botanical-fade.png' })
await expect(foliage).toHaveCSS('opacity', '1')
await expect(foliageArt.locator('path').first()).toHaveCSS('stroke-dasharray', 'none')
const clearAction = page.locator('.booking-panel').first().getByRole('button', { name: 'Book Mobile', exact: true })
await clearAction.click()
await expect(page.getByRole('dialog')).toBeVisible()
await page.keyboard.press('Escape')
await expect(page.getByRole('dialog')).toBeHidden()
await page.locator('.header-logo').click()
await expect(foliage).toHaveCSS('opacity', '1')
evidence.push('Olive branches and lavender share four background layers and the centered fade; decoration waits for the center, fades through intermediate opacity, stays visible afterwards, and leaves booking usable')

await firstService.scrollIntoViewIfNeeded()
await expect(firstService).toHaveCSS('opacity', '1')
await expect(page.locator('.desktop-nav a[href="#services"]')).toHaveAttribute('aria-current', 'location')
evidence.push('An offscreen service becomes fully visible when scrolled into view; navigation identifies Services')
await expect(plants.nth(1).locator('svg').first()).toHaveCSS('opacity', '0.1')
await expect(plants.nth(1)).toHaveCSS('opacity', '1')
await page.locator('.services-intro').evaluate(el => el.scrollIntoView({ block: 'start', behavior: 'instant' }))
await page.screenshot({ path: 'test-results/desktop-services.png' })
evidence.push('Olive leaves and lavender fade in together with the centered treatment section and retain low-opacity artwork')

await firstService.getByRole('button', { name: 'Book now' }).click()
await expect(page.getByRole('dialog')).toBeVisible()
await page.keyboard.press('Escape')
await expect(page.getByRole('dialog')).toBeHidden()
evidence.push('Booking remains usable during normal motion; dialog opens and Escape closes it')

await page.locator('.header-logo').click()
await expect(firstService).toHaveCSS('opacity', '1')
evidence.push('Previously revealed content stays visible after scrolling away')
await page.emulateMedia({ reducedMotion: 'reduce' })
await page.waitForFunction(() => [...document.querySelectorAll('[data-reveal]')].every(el => getComputedStyle(el).opacity === '1'))
await expect(page.locator('.hero-content')).toHaveCSS('animation-name', 'none')
assert.equal(await plants.evaluateAll(elements => elements.every(el => getComputedStyle(el).opacity === '1' && getComputedStyle(el).transitionDuration === '0s')), true)
evidence.push('Changing to reduced motion immediately reveals all content and disables the hero animation')

await page.emulateMedia({ reducedMotion: 'no-preference' })
await page.setViewportSize({ width: 375, height: 812 })
await page.goto('http://localhost:5173', { waitUntil: 'networkidle' })
await expect(foliage).toHaveCSS('opacity', '0')
await page.locator('#booking-options').evaluate(el => scrollTo({ top: scrollY + el.getBoundingClientRect().top - innerHeight * .7, behavior: 'instant' }))
await expect(foliage).toHaveCSS('opacity', '0')
await page.locator('#booking-options').evaluate(el => scrollTo({ top: scrollY + el.getBoundingClientRect().top - innerHeight * .5, behavior: 'instant' }))
await expect(foliage).toHaveCSS('opacity', '1')
evidence.push('Phone botanical fade also waits for the section to reach the center of the screen')
await page.getByRole('button', { name: 'Menu', exact: true }).click()
await expect(page.getByRole('navigation', { name: 'Mobile navigation' })).toHaveCSS('opacity', '1')
await page.keyboard.press('Escape')
await expect(page.getByRole('navigation', { name: 'Mobile navigation' })).toBeHidden()
evidence.push('Animated phone menu settles visibly and closes with Escape')

await page.addInitScript(() => { delete window.IntersectionObserver })
await page.reload({ waitUntil: 'networkidle' })
assert.equal(await page.locator('[data-reveal]').evaluateAll(elements => elements.every(el => getComputedStyle(el).opacity === '1')), true)
assert.equal(await plants.evaluateAll(elements => elements.every(el => getComputedStyle(el).opacity === '1')), true)
evidence.push('When IntersectionObserver is unavailable, all page content remains visible')
for (const [name, selector] of [['booking', '.booking-intro'], ['services', '.services-intro'], ['about', '.about-content']]) {
  await page.locator(selector).evaluate(el => el.scrollIntoView({ block: 'center', behavior: 'instant' }))
  await page.screenshot({ path: `test-results/mobile-botanical-${name}.png` })
}
assert.deepEqual(errors, [])
await writeFile('test-results/motion-check.json', JSON.stringify({ evidence, errors }, null, 2))
console.log(evidence.join('\n'))
await browser.close()
