import { mockContact } from './mock-contact.mjs'
import { chromium, expect } from '@playwright/test'
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'

await mkdir('test-results', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome' })
const evidence = [], errors = []
const roles = ['Registered Massage Therapist (RMT)', 'Osteopathic Therapist', 'Acupuncturist', 'Lymphatic Drainage Therapist']
const resume = { name: 'résumé.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.7\nCareer resume — attachment verification\n%%EOF') }

function luminance(rgb) {
  return rgb.map(value => value / 255).map(value => value <= .04045 ? value / 12.92 : ((value + .055) / 1.055) ** 2.4).reduce((sum, value, index) => sum + value * [.2126, .7152, .0722][index], 0)
}
function contrast(a, b) {
  const values = [luminance(a), luminance(b)].sort((x, y) => y - x)
  return (values[0] + .05) / (values[1] + .05)
}

try {
  const page = await browser.newPage()
  await mockContact(page)
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  for (const width of [320, 375, 600, 768, 1024, 1280, 1440, 1900]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('http://localhost:5173', { waitUntil: 'networkidle' })
    if (width < 1280) await page.getByRole('button', { name: 'Menu', exact: true }).click()
    const nav = page.locator(width < 1280 ? '.mobile-nav' : '.desktop-nav')
    await expect(nav.getByRole('link', { name: 'CAREERS', exact: true })).toHaveAttribute('href', '/careers')
    await nav.getByRole('link', { name: 'CAREERS', exact: true }).click()
    await expect(page).toHaveURL('http://localhost:5173/careers')
    await page.waitForLoadState('networkidle')
    await expect(page).toHaveTitle('Careers | Mielle Wellness')
    await expect(page.locator('.site-header')).toHaveClass(/is-solid/)
    await expect(page.locator('.desktop-nav a[href="/careers"]')).toHaveAttribute('aria-current', 'page')
    await expect(page.getByRole('heading', { name: 'Careers', exact: true })).toBeVisible()
    await expect(page.locator('.careers-hero-copy > p')).toHaveText('Seeking a Career at Mielle Wellness')
    await expect(page.locator('.career-opportunities li')).toHaveText(roles)
    await expect(page.locator('.careers-welcome > p')).toHaveText('At Mielle Wellness, we pride ourselves on fostering a clean, welcoming, and respectful environment for both our clients and our team. Our dedication to helping clients achieve their physical well-being, relieve tension, and restore balance is at the heart of everything we do. We are committed to creating a space where relaxation, care, and professionalism come together in every experience.')
    await page.evaluate(() => document.fonts.ready)
    const hero = await page.locator('.careers-hero').boundingBox(), header = await page.locator('.site-header').boundingBox()
    assert.ok(hero.y >= header.height)
    const poster = page.locator('.careers-poster img')
    await poster.scrollIntoViewIfNeeded()
    await expect.poll(() => poster.evaluate(el => el.complete && el.naturalWidth === 2550)).toBe(true)
    await expect(page.locator('.careers-hero > img')).toHaveAttribute('src', '/assets/careers-body-scrub.jpg')
    await expect.poll(() => page.locator('.careers-hero > img').evaluate(el => ({ complete: el.complete, width: el.naturalWidth, height: el.naturalHeight }))).toEqual({ complete: true, width: 7190, height: 4799 })
    const imageBounds = await poster.boundingBox(), copyBounds = await page.locator('.careers-welcome').boundingBox()
    if (width >= 680) assert.ok(copyBounds.x >= imageBounds.x + imageBounds.width)
    else assert.ok(copyBounds.y >= imageBounds.y + imageBounds.height)
    const apply = page.getByRole('link', { name: 'Apply Now', exact: true })
    assert.ok((await apply.boundingBox()).height >= 44)
    await apply.focus()
    await page.keyboard.press('Enter')
    await expect(page).toHaveURL('http://localhost:5173/careers#application')
    await expect(page.locator('#application-first-name')).toBeFocused()
    await expect(page.locator('#application-first-name')).toBeInViewport()
    await expect(page.locator('#application')).toHaveCSS('opacity', '1')
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
    for (const control of await page.locator('.application-fields input:not([type=file]):not([type=hidden]), .application-fields textarea, .resume-upload, .career-country-trigger').all()) assert.ok((await control.boundingBox()).height >= 44)
    const country = page.getByRole('button', { name: 'Phone country: Canada (+1)', exact: true })
    await country.click()
    await expect(page.getByRole('combobox', { name: 'Search phone countries' })).toBeFocused()
    await expect(page.getByRole('option', { name: 'Canada +1', exact: true })).toHaveAttribute('aria-selected', 'true')
    await expect.poll(async () => {
      const panel = await page.locator('.career-country-panel').boundingBox()
      return panel.x >= 0 && panel.x + panel.width <= width && panel.y >= 0 && panel.y + panel.height <= 900
    }).toBe(true)
    assert.ok(await page.locator('.career-country-trigger img').evaluate(el => el.complete && el.naturalWidth > 0))
    await page.keyboard.press('Escape')
    await expect(country).toBeFocused()
    await expect(page.locator('.career-country-panel')).toHaveCount(0)
    assert.equal(await page.locator('.about-contact').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(0, 0, 0)')
    assert.equal(await page.locator('.site-footer').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(0, 0, 0)')
    if ([375, 1900].includes(width)) {
      await page.locator('#contact').scrollIntoViewIfNeeded()
      await page.locator('.site-footer').scrollIntoViewIfNeeded()
      await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }))
      await page.screenshot({ path: `test-results/careers-${width}.png`, fullPage: true })
    }
    await page.getByRole('button', { name: 'Submit', exact: true }).click()
    assert.equal(await page.locator('.application-form').evaluate(el => el.checkValidity()), false)
    await expect(page.locator('#application-first-name')).toBeFocused()
    evidence.push(`${width}px: header opens local /careers with active marker/title, original images and exact copy, responsive columns, four roles, Apply Now keyboard/anchor/focus, empty form validation, usable controls, black contact/footer, no overflow`)
  }
  console.log('Careers layouts and phone positioning passed; checking native resume submission.')
  const form = page.locator('.application-form')
  await form.getByLabel('First name', { exact: false }).fill('Zoë')
  await form.getByLabel('Last name', { exact: false }).fill('Applicant')
  await form.getByLabel('Email', { exact: false }).fill('zoe@example.com')
  await page.locator('#application-phone').fill('letters')
  assert.equal(await page.locator('#application-phone').evaluate(el => el.checkValidity()), false)
  await page.locator('#application-phone').fill('8254078617')
  assert.equal(await page.locator('#application-phone').evaluate(el => el.checkValidity()), true)
  await page.getByRole('button', { name: 'Phone country: Canada (+1)' }).click()
  await page.getByRole('combobox', { name: 'Search phone countries' }).fill('no matching country')
  await expect(page.getByRole('status').filter({ hasText: 'No countries found.' })).toBeVisible()
  await page.keyboard.press('Enter')
  await expect(page.locator('.application-feedback')).toHaveCount(0)
  await page.getByRole('combobox', { name: 'Search phone countries' }).fill('France')
  await expect(page.getByRole('option', { name: 'France +33', exact: true })).toBeVisible()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('button', { name: 'Phone country: France (+33)' })).toBeFocused()
  await page.locator('#application-phone').fill('0612345678')
  assert.equal(await page.locator('#application-phone').evaluate(el => el.checkValidity()), true)
  await form.getByLabel('Message', { exact: false }).fill('I’m applying for the Registered Massage Therapist role.\nThank you — Zoë.')
  const upload = page.locator('#application-resume')
  await upload.focus()
  await expect(page.locator('.resume-upload')).toHaveCSS('outline-style', 'solid')
  const chooserPromise = page.waitForEvent('filechooser')
  await page.keyboard.press('Space')
  await (await chooserPromise).setFiles(resume)
  await expect(page.locator('#resume-filename')).toHaveText(resume.name)
  await upload.setInputFiles({ name: 'resume.txt', mimeType: 'text/plain', buffer: Buffer.from('Unsupported resume') })
  await expect(page.locator('#resume-error')).toHaveText('Choose a PDF, DOC or DOCX resume.')
  assert.equal(await form.evaluate(el => el.checkValidity()), false)
  await upload.setInputFiles({ name: 'empty.pdf', mimeType: 'application/pdf', buffer: Buffer.alloc(0) })
  await expect(page.locator('#resume-error')).toHaveText('This file is empty. Choose your resume again.')
  await upload.setInputFiles({ name: 'large.pdf', mimeType: 'application/pdf', buffer: Buffer.alloc(10 * 1024 * 1024 + 1) })
  await expect(page.locator('#resume-error')).toHaveText('Choose a resume smaller than 10 MB.')
  await upload.setInputFiles(resume)
  await expect(page.locator('#resume-error')).toHaveCount(0)
  assert.equal(await form.evaluate(el => el.checkValidity()), true)
  let submitted, release
  let outcome = 'pending'
  await page.route('https://formsubmit.co/miellewellness@gmail.com', async route => {
    const request = route.request()
    assert.equal(request.method(), 'POST')
    assert.equal(request.isNavigationRequest(), true)
    assert.match(request.headers()['content-type'], /^multipart\/form-data; boundary=/)
    submitted = await new Request(request.url(), { method: 'POST', headers: request.headers(), body: request.postDataBuffer() }).formData()
    if (outcome === 'pending') await new Promise(resolve => { release = resolve })
    if (outcome === 'activation') {
      await route.fulfill({ contentType: 'text/html', body: '<h1>Confirm your email to activate this form</h1>' })
      return
    }
    await route.fulfill({ status: 303, headers: { location: String(submitted.get('_next')) } })
  })
  await expect(form).toHaveAttribute('action', 'https://formsubmit.co/miellewellness@gmail.com')
  await expect(form).toHaveAttribute('method', 'POST')
  await expect(form).toHaveAttribute('enctype', 'multipart/form-data')
  await page.getByRole('button', { name: 'Submit', exact: true }).click({ noWaitAfter: true })
  await expect.poll(() => !!release).toBe(true)
  assert.equal(submitted.get('name'), 'Zoë Applicant')
  assert.equal(submitted.get('_subject'), 'Mielle Wellness | Career application from Zoë Applicant')
  assert.equal(submitted.get('_template'), 'table')
  assert.equal(submitted.get('_url'), 'http://localhost:5173/careers#application')
  assert.equal(submitted.get('_next'), 'http://localhost:5173/careers?application=submitted#application')
  assert.equal(submitted.has('firstName'), false)
  assert.equal(submitted.has('lastName'), false)
  assert.equal(submitted.has('phoneCountry'), false)
  assert.equal(submitted.get('phone'), '+33 6 12 34 56 78')
  assert.equal(submitted.get('attachment').name, resume.name)
  assert.deepEqual(Buffer.from(await submitted.get('attachment').arrayBuffer()), resume.buffer)
  release()
  await expect(page.locator('.application-feedback')).toContainText('Your application has been submitted.')
  await expect(page).toHaveURL('http://localhost:5173/careers#application')
  await expect(form).toHaveAttribute('aria-busy', 'false')
  for (const id of ['application-first-name', 'application-last-name', 'application-email', 'application-phone', 'application-message']) await expect(page.locator(`#${id}`)).toHaveValue('')
  assert.equal(await upload.evaluate(el => el.files.length), 0)
  await expect(page.locator('#resume-filename')).toHaveText('')
  await expect(page.locator('input[name="phoneCountry"]')).toHaveValue('CA')
  await page.getByRole('button', { name: 'Phone country: Canada (+1)' }).click()
  await page.getByRole('combobox', { name: 'Search phone countries' }).fill('France')
  await page.keyboard.press('Enter')
  await expect(page.locator('.application-feedback')).toHaveCount(0)
  await form.getByLabel('First name', { exact: false }).fill('Zoë')
  await form.getByLabel('Last name', { exact: false }).fill('Applicant')
  await form.getByLabel('Email', { exact: false }).fill('zoe@example.com')
  await upload.setInputFiles(resume)
  await page.locator('#application-phone').fill('+1 (825) 407-8617')
  await expect(page.getByRole('button', { name: 'Phone country: Canada (+1)' })).toBeVisible()
  await form.getByLabel('Message', { exact: false }).fill('Updated application')
  outcome = 'activation'
  await page.getByRole('button', { name: 'Submit', exact: true }).click()
  await expect(page).toHaveURL('https://formsubmit.co/miellewellness@gmail.com')
  await expect(page.getByRole('heading')).toHaveText('Confirm your email to activate this form')
  await expect(page.locator('.application-feedback')).toHaveCount(0)
  await page.goBack({ waitUntil: 'networkidle' })
  await expect(page.getByRole('button', { name: 'Submit', exact: true })).toBeEnabled()
  await expect(page.locator('.application-feedback')).toHaveCount(0)
  await page.setViewportSize({ width: 375, height: 900 })
  await form.getByLabel('First name', { exact: false }).fill('Zoë')
  await form.getByLabel('Last name', { exact: false }).fill('Applicant')
  await form.getByLabel('Email', { exact: false }).fill('zoe@example.com')
  await page.locator('#application-phone').fill('+1 (825) 407-8617')
  const wordResume = { name: 'résumé.docx', mimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', buffer: Buffer.from('PK\x03\x04Career Word resume bytes') }
  await upload.setInputFiles(wordResume)
  await form.getByLabel('Message', { exact: false }).fill('')
  assert.equal(await page.locator('#application-message').evaluate(el => el.required), false)
  assert.equal(await form.evaluate(el => el.checkValidity()), true)
  outcome = 'success'
  await page.getByRole('button', { name: 'Submit', exact: true }).click()
  await expect(page.locator('.application-feedback')).toBeVisible()
  assert.equal(submitted.get('message'), '')
  assert.equal(submitted.get('attachment').name, wordResume.name)
  assert.deepEqual(Buffer.from(await submitted.get('attachment').arrayBuffer()), wordResume.buffer)
  await expect(form.getByRole('alert')).toHaveCount(0)
  for (const id of ['application-first-name', 'application-last-name', 'application-email', 'application-phone', 'application-message']) await expect(page.locator(`#${id}`)).toHaveValue('')
  assert.equal(await upload.evaluate(el => el.files.length), 0)
  await expect(page.locator('#resume-filename')).toHaveText('')
  evidence.push('Phone/country keyboard controls, national and international validation, resume type/empty/10 MB validation and keyboard upload pass. Native multipart POST to the documented FormSubmit upload endpoint preserves UTF-8 name, exact PDF and DOCX bytes, filename and international phone. The file input stays enabled during serialization. An activation page shows no success; browser Back permits retry. Optional blank application message submits at 375px. Mocked acceptance returns to Careers, clears every field/file and resets Canada. No live email or provider attachment delivery is tested.')

  const ratios = {
    body: contrast([40, 46, 32], [255, 255, 255]),
    muted: contrast([99, 104, 90], [255, 255, 255]),
    action: contrast([255, 255, 255], [99, 102, 86]),
    actionHover: contrast([255, 255, 255], [78, 81, 67]),
    heroWorstCase: contrast([255, 255, 255], [112.2, 112.2, 112.2]),
  }
  assert.ok(Object.values(ratios).every(ratio => ratio >= 4.5))
  await page.goto('http://localhost:5173/careers/', { waitUntil: 'networkidle' })
  await page.setViewportSize({ width: 1900, height: 900 })
  await page.reload({ waitUntil: 'networkidle' })
  await expect(page).toHaveTitle('Careers | Mielle Wellness')
  await page.locator('.desktop-nav').getByRole('link', { name: 'CONTACT', exact: true }).click()
  await expect(page).toHaveURL('http://localhost:5173/careers/#contact')
  await page.getByRole('button', { name: 'SEND', exact: true }).click()
  assert.equal(await page.locator('.contact-form').evaluate(el => el.checkValidity()), false)
  await page.locator('#first-name').fill('Career enquiry')
  await page.locator('#contact-email').fill('enquiry@example.com')
  await page.locator('#message').fill('Career enquiry')
  await page.getByRole('button', { name: 'SEND', exact: true }).click()
  await expect(page.locator('.contact-form .form-feedback')).toContainText('Your message has been submitted.')
  await expect(page.locator('.site-footer form')).toHaveCount(0)
  const bookingControl = page.locator('.footer-navigation').getByRole('link', { name: 'Booking', exact: true })
  await expect(bookingControl).toHaveAttribute('href', 'https://miellewellness.noterro.com/')
  await expect(bookingControl).toHaveAttribute('target', '_blank')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('http://localhost:5173/careers', { waitUntil: 'networkidle' })
  await expect(page.locator('.careers-hero-copy')).toHaveCSS('animation-name', 'none')
  await expect(page.locator('.careers-welcome')).toHaveCSS('opacity', '1')
  await page.getByRole('link', { name: 'Apply Now', exact: true }).click()
  await expect(page.locator('#application-first-name')).toBeFocused()
  await page.locator('.desktop-nav').getByRole('link', { name: 'HOME', exact: true }).click()
  await expect(page).toHaveURL('http://localhost:5173/#home')
  await page.goBack({ waitUntil: 'networkidle' })
  await expect(page).toHaveURL('http://localhost:5173/careers#application')
  evidence.push('Direct route, trailing slash, refresh, local Contact, required contact messages and mocked FormSubmit submissions, direct footer Noterro booking link, reduced motion, Home/history, and AA text contrast pass; footer subscription form is removed')
  assert.deepEqual(errors, [])
  await writeFile('test-results/careers-check.json', JSON.stringify({ evidence, ratios, errors }, null, 2))
  console.log(evidence.join('\n'))
} finally {
  await browser.close()
}
