import { mockContact } from './mock-contact.mjs'
import { chromium, expect } from '@playwright/test'
import assert from 'node:assert/strict'
import { mkdir, writeFile } from 'node:fs/promises'

await mkdir('test-results', { recursive: true })
const browser = await chromium.launch({ channel: 'chrome' })
const evidence = [], errors = []
const headings = ["DON'T LOSE YOUR COVERAGE", 'COMPASSIONATE MASSAGE CARE FOR SENIORS', 'FIRST VISIT SPECIAL AT MIELLE WELLNESS']
try {
  const page = await browser.newPage()
  await mockContact(page)
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  for (const width of [320, 375, 600, 768, 1024, 1280, 1440, 1900]) {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('http://localhost:5173', { waitUntil: 'networkidle' })
    if (width < 1280) await page.getByRole('button', { name: 'Menu', exact: true }).click()
    const nav = page.locator(width < 1280 ? '.mobile-nav' : '.desktop-nav')
    await nav.getByRole('link', { name: 'PROMOS', exact: true }).click()
    await expect(page).toHaveURL('http://localhost:5173/promos')
    await expect(page).toHaveTitle('Promos | Mielle Wellness')
    await expect(page.locator('.site-header')).toHaveClass(/is-solid/)
    await expect(page.locator('.desktop-nav a[href="/promos"]')).toHaveAttribute('aria-current', 'page')
    await expect(page.getByRole('heading', { name: 'PROMOS', exact: true })).toBeVisible()
    await expect(page.locator('.promos-hero-copy > p')).toHaveText('Stay Updated with Our Promos & Events')
    await expect(page.getByRole('dialog')).toHaveCount(0)
    await expect(page.locator('.promotion h2')).toHaveText(headings)
    await expect(page.locator('.promotion-number')).toHaveText(['01', '02', '03'])
    await expect(page.locator('.promotion-copy > p')).toHaveCount(5)
    await expect(page.locator('.promotion-copy')).toContainText(['Your benefits won’t last forever', 'Professional, caring and convenient', 'new clients receive 10% OFF their first visit'])
    await page.evaluate(() => document.fonts.ready)
    const header = await page.locator('.site-header').boundingBox()
    const hero = await page.locator('.promos-hero').boundingBox()
    assert.ok(hero.y >= header.height)
    for (let i = 0; i < headings.length; i++) {
      const promotion = page.locator('.promotion').nth(i)
      const image = promotion.locator('img')
      await image.scrollIntoViewIfNeeded()
      await expect.poll(() => image.evaluate(el => el.complete && el.naturalWidth > 0)).toBe(true)
      const imageBounds = await image.boundingBox(), copyBounds = await promotion.locator('.promotion-copy').boundingBox()
      if (width >= 1100 && i === 1) assert.ok(copyBounds.x >= imageBounds.x + imageBounds.width)
      else if (width >= 680) assert.ok(imageBounds.x >= copyBounds.x + copyBounds.width)
      else assert.ok(imageBounds.y >= copyBounds.y + copyBounds.height)
      const button = promotion.getByRole('link', { name: 'BOOK NOW', exact: true })
      assert.ok((await button.boundingBox()).height >= 44)
      await button.focus()
      await expect(button).toHaveAttribute('href', '/services')
      await page.keyboard.press('Enter')
      await page.waitForURL('**/services')
      await expect(page.locator('.treatment-card')).toHaveCount(8)
      await page.goBack({ waitUntil: 'networkidle' })
      await page.waitForURL('**/promos')
      await promotion.scrollIntoViewIfNeeded()
      await expect(promotion.locator('.promotion-copy')).toHaveCSS('opacity', '1')
      await expect(promotion.locator('.promotion-art')).toHaveCSS('opacity', '1')
    }
    await expect(page.locator('.promos-hero > img')).toHaveAttribute('src', '/assets/promos-herbal-massage.jpeg')
    assert.ok(await page.locator('.promos-hero > img').evaluate(el => el.complete && el.naturalWidth === 683 && el.naturalHeight === 1024))
    await expect(page.locator('#contact')).toHaveCount(0)
    assert.equal(await page.locator('.site-footer').evaluate(el => getComputedStyle(el).backgroundColor), 'rgb(0, 0, 0)')
    await expect(page.locator('.site-footer form')).toHaveCount(0)
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth))
    if ([375, 1900].includes(width)) {
      await page.evaluate(() => scrollTo({ top: 0, behavior: 'instant' }))
      await page.screenshot({ path: `test-results/promos-${width}.png`, fullPage: true })
    }
    evidence.push(`${width}px: navbar opens /promos, active page, exact headings/copy, original images, responsive/alternating rows, completed scroll reveals, all three Book Now links reach /services by keyboard, no contact block, black footer, no overflow`)
  }
  await page.goto('http://localhost:5173/promos', { waitUntil: 'networkidle' })
  const artwork = page.locator('.promotion-art').first()
  await artwork.hover()
  await expect(artwork.locator('img')).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, -6)')
  await page.mouse.move(0, 0)
  await expect(artwork.locator('img')).toHaveCSS('transform', 'none')
  await page.locator('.promotion-booking').first().hover()
  await expect(page.locator('.promotion-booking').first()).toHaveCSS('transform', 'matrix(1, 0, 0, 1, 0, -2)')
  await page.mouse.move(0, 0)
  await expect(page.locator('.promotion-booking').first()).toHaveCSS('transform', 'none')
  evidence.push('Proximity groups numbered headings, copy and actions; aligned rules and alternating artwork establish continuity and balance. Artwork/button hover transitions return smoothly on mouse-out')
  await page.goto('http://localhost:5173/promos/', { waitUntil: 'networkidle' })
  await expect(page).toHaveTitle('Promos | Mielle Wellness')
  await page.reload({ waitUntil: 'networkidle' })
  await expect(page.getByRole('heading', { name: 'PROMOS', exact: true })).toBeVisible()
  await page.locator('.desktop-nav').getByRole('link', { name: 'CONTACT', exact: true }).click()
  await expect(page).toHaveURL('http://localhost:5173/#contact')
  await expect(page.locator('#contact')).toBeInViewport()
  await page.getByRole('button', { name: 'SEND', exact: true }).click()
  assert.equal(await page.locator('.contact-form').evaluate(el => el.checkValidity()), false)
  await page.getByLabel('First name').fill('Promo enquiry')
  await page.locator('input[name="email"]').fill('promo@example.com')
  await page.locator('#message').fill('A question about the first visit promotion.')
  await page.getByRole('button', { name: 'SEND', exact: true }).click()
  await expect(page.locator('.contact-form .form-feedback')).toContainText('Your message has been submitted.')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('http://localhost:5173/promos', { waitUntil: 'networkidle' })
  await expect(page.locator('.promos-hero-copy')).toHaveCSS('animation-name', 'none')
  await page.locator('.promotion-art').first().hover()
  await expect(page.locator('.promotion-art img').first()).toHaveCSS('transform', 'none')
  await expect(page.locator('.promotion-art img').first()).toHaveCSS('transition-duration', '0s')
  await expect(page.getByRole('heading', { name: 'PROMOS', exact: true })).toBeVisible()
  await page.locator('.promotion-booking').last().click()
  await page.waitForURL('**/services')
  await page.goBack({ waitUntil: 'networkidle' })
  await page.waitForURL('**/promos')
  await page.locator('.desktop-nav').getByRole('link', { name: 'HOME', exact: true }).click()
  await expect(page).toHaveURL('http://localhost:5173/#home')
  await page.goBack({ waitUntil: 'networkidle' })
  await expect(page).toHaveURL('http://localhost:5173/promos')
  await expect(page.getByRole('heading', { name: 'PROMOS', exact: true })).toBeVisible()
  evidence.push('Direct loading, trailing slash, refresh, Contact link to Home, mocked contact submission, reduced motion, Home and browser history pass; footer subscription form is removed; no messages sent')
  assert.deepEqual(errors, [])
  await writeFile('test-results/promos-check.json', JSON.stringify({ evidence, errors }, null, 2))
  console.log(evidence.join('\n'))
} finally {
  await browser.close()
}
